### ISSUE TITLE
动态路径无法识别

### ISSUE THREAD

**Issue by ldwonday** [Cap32/wxapp-webpack-plugin#10]
如题，假如我在page引用了一个自定义组件，组件有一个image接收一个imageSrc的src路径，在page中传过去imageSrc到组件，这个路径不会被webpack解析到，导致图片出不来，有解决方案吗？

**Comment by Cap32** [comment]
可以参考 [Webpack Dependency Management](https://webpack.js.org/guides/dependency-management/#require-context)，或者使用 [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin) 描述需要 copy 到 dist 的文件。

希望能帮到你
