### ISSUE TITLE
不支持绝对定位的写法

### ISSUE THREAD

**Issue by YangTingWei** [Cap32/wxapp-webpack-plugin#14]
组件，或者模板是不是不能支持绝对定位的写法，能不能改成同时支持呢？

**Comment by Cap32** [comment]
不支持，原因是 Webpack 不支持绝对路径写法

**Comment by Cap32** [comment]
可以在 webpack 上配置 [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules)，然后把 '/my/path' 改为 'my/path' 即可实现类似效果
