### ISSUE TITLE
打包后注释警告还在

### ISSUE THREAD

**Issue by axy541877028** [Cap32/wxapp-webpack-plugin#17]
请问怎么去除 使用  
  // new webpack.optimize.UglifyJsPlugin({
    //   comments: false, //去掉注释
    //   compress: {
    //     warnings: false //忽略警告，不然会有一大推的黄色字体出现
    //   }
    // })
没作用

**Comment by Cap32** [comment]
Duplicated https://github.com/cantonjs/wxapp-boilerplate/issues/31
