### ISSUE TITLE
md文件中wxml-loader的跳转是正确的嘛？

### ISSUE THREAD

**Issue by Windancer** [Cap32/wxapp-webpack-plugin#2]

**Comment by Cap32** [comment]
wxml-loader 不属于这个项目，要实现完整的项目开发请参考 https://github.com/cantonjs/wxapp-boilerplate 如果你希望得到帮助或提出 bug，请提供更详细的信息，例如重现方式，环境，出错信息等等

**Comment by Windancer** [comment]
MD文件中关于wxml-loader和file-loader的描述，都跳转到了同一个链接下。
但是file-loader并不能编译或处理 *.wxml文件。所以我确认下是否有误。
另：引入wxapp-webpack-plugin插件，并没有安装对应编译依赖我通过-D的方式安装后正常。
我是win8 64位OS ，npm 5/node 6.10

**Comment by Cap32** [comment]
我把这个项目 README 上关于完整项目 webpack 配置的部分删掉了，因为它超出这个项目范畴。关于完整 webpack 完整配置还是建议参考 https://github.com/cantonjs/wxapp-boilerplate 如果 webpack 配置有误请在 https://github.com/cantonjs/wxapp-boilerplate/issues 提出

**Comment by Windancer** [comment]
你完全没明白我的意思，我服了。

**Comment by anchengjian** [comment]
这哥们的意思是项目介绍的文档中 `README.MD` 文件中
```
- [wxml-loader](https://github.com/webpack-contrib/file-loader): 使 `webpack` 能编译或处理 `*.wxml` 上引用的文件
```

这个链接放错了，写成了和 `file-loader` 一样的了

**Comment by Cap32** [comment]
@anchengjian 谢谢你，已修复 👍🏿
