### ISSUE TITLE
建议添加全局组件功能，使用async的时候，错误没有被捕捉

### ISSUE THREAD

**Issue by XLinzexin** [Cap32/wxapp-webpack-plugin#21]

**Comment by Cap32** [comment]
> 建议添加全局组件功能

这功能超出了这个库的目标范畴了

> 使用async的时候，错误没有被捕捉

感谢反馈。之前版本的 [wxapp-boilerplate](https://github.com/cantonjs/wxapp-boilerplate) 
是因为 babel inject 了 promise polyfill 导致了这个问题，现在修复了。只需要在 `.babelrc` 上把 `transform-runtime` 的 `polyfill` 设为 [false](https://github.com/cantonjs/wxapp-boilerplate/blob/4d60af03e3caec36dd8ca6eb04d07951af42ff86/.babelrc#L15)，采用微信小程序原生的 promise 即可

**Comment by XLinzexin** [comment]
试了把transform-runtime 的polyfill设为false没有用，但同时把transform-runtime 的helpers也设为false，错误就可以正常捕捉
