### ISSUE TITLE
没明白？这是咋用的？

### ISSUE THREAD

**Issue by kuailingmin** [Cap32/wxapp-webpack-plugin#27]
这个插件具体做什么用的？

**Comment by Cap32** [comment]
> 为什么要使用这个插件
> 
> - 微信小程序开发需要有多个入口文件（如 `app.js`, `app.json`, `pages/index/index.js` 等等），使用这个插件只需要引入 `app.js` 即可，其余文件将会被自动引入
> - 若多个入口文件（如 `pages/index/index.js` 和 `pages/logs/logs.js`）引入有相同的模块，这个插件能避免重复打包相同模块
> - 支持自动复制 `app.json` 上的 `tabbar` 图片
