### ISSUE TITLE
小程序 新出的 Components 

### ISSUE THREAD

**Issue by sin-ning** [Cap32/wxapp-webpack-plugin#3]
小程序的自定义 component 在 json 中定义 usingComponents，没有引用不能 build 过去。

**Comment by Cap32** [comment]
谢谢反馈，已添加到下个版本计划中

**Comment by Cap32** [comment]
已经 merge https://github.com/Cap32/wxapp-webpack-plugin/pull/5 ，并且已发布 `v0.16.0` 至 npm
