### ISSUE TITLE
typescript支持的问题

### ISSUE THREAD

**Issue by xuming314** [Cap32/wxapp-webpack-plugin#6]
设置脚本后缀支持.ts文件：new WXAppWebpackPlugin({clear:!isDev, scriptExt:'.ts'})
但entry里还是必须设置app.js为.js后缀：entry: {app: [ './src/app.js']}
问题在以下源代码，写死了app.js：（建议支持动态options.scriptExt）
const getEntryFromCompiler = () => {
  if (typeof entry === 'string') return entry;
  const appJSRegExp = /\bapp(\.js)?$/;
  const findAppJS = arr => arr.find(path => appJSRegExp.test(path));
  if (Array.isArray(entry)) return findAppJS(entry);
  if (typeof entry === 'object') {
    for (const key in entry) {
      if (!entry.hasOwnProperty(key)) continue;
      const val = entry[key];
      if (typeof val === 'string') return val;
      if (Array.isArray(val))  return findAppJS(val);
    }
  }
};

**Comment by Cap32** [comment]
`v0.17` 57650a3fcc1e52580a53ec24e577f3ceb5456ff5 解决了这个问题，已发布到 npm。

新增 `extensions` 配置选项，通过配置 `extensions: ['.ts', '.js']` 可以实现。

感谢反馈 👍🏿
